import type { Metadata } from "next";
import Image from "next/image";
import { DIMENSIONS } from "@/lib/domain/schemas";
import { WEIGHTS } from "@/lib/domain/scoring";
import { formatLabel } from "@/lib/format";

export const metadata: Metadata = { title: "Methodology", description: "How InvestorStack selects, scores and updates tools." };

export default function MethodologyPage() {
  return <><header className="hero" style={{ minHeight: 470 }}><Image className="hero-image" src="/images/orchard-hero.jpg" alt="Cultivated valley" fill unoptimized sizes="100vw" /><div className="site-container hero-content"><div className="hero-copy"><span className="eyebrow">Methodology v0.1</span><h1 className="display page-title">Scores are useful only when the evidence is visible.</h1><p className="lede">InvestorStack evaluates fit for investment workflows, not generic software quality. Scores are derived, confidence-labelled and separated from commercial activity.</p></div></div></header><section className="site-container section"><div className="rule-title"><h2>Seven weighted dimensions</h2><span className="meta">Total weight 100</span></div>{DIMENSIONS.map((dimension) => <div className="score-row" key={dimension}><span>{formatLabel(dimension)}</span><div className="score-track"><div className="score-fill" style={{ width: `${WEIGHTS[dimension]}%` }} /></div><span className="mono">{WEIGHTS[dimension]}</span></div>)}</section><section className="section section-rule"><div className="site-container split-grid"><div><span className="eyebrow">AI readiness</span><h2 className="display section-title" style={{ marginTop: 10 }}>Interfaces, not AI feature theatre.</h2></div><div><p className="lede">The pass-1 signal records public API access, MCP support, webhooks, structured exports and authentication. Tier-gating and write access require direct verification before a full score is published.</p></div></div></section><section className="site-container section"><div className="split-grid"><div><div className="rule-title"><h2>Selection and updates</h2></div><p className="lede">The initial universe is capped at five tools per category. New tools enter when they materially change the decision set. Vendor and user corrections enter review; no score changes automatically.</p></div><div><div className="rule-title"><h2>Trust and limitations</h2></div><p className="lede">Meeting Memory is the only provisionally scored category. Other tools show facts and signals without numeric stand-ins. Paid profiles and introductions can be labelled, but can never change rank or verdict.</p></div></div></section></>;
}
